-- Run the below functions when you want to set up a new bot

-- Create a bucket called images

create table public.users (
  id bigint not null,
  created_at timestamp with time zone not null default now(),
  tokens numeric not null default '500' :: numeric,
  settings jsonb not null default '{"nsfw": false, "description": null}' :: jsonb,
  username text null,
  first_name text null,
  last_name text null,
  language_code text not null default 'en' :: text,
  onboarding boolean not null default true,
  last_updated bigint null,
  constraint users_pkey primary key (id)
) tablespace pg_default;

create table
  public.conversations (
    id bigint generated by default as identity,
    type text not null default 'message'::text,
    text text null,
    "user" bigint null,
    ts bigint not null,
    rating bigint null default '1'::bigint,
    constraint conversations_pkey primary key (id),
    constraint conversations_user_fkey foreign key ("user") references users (id) on delete cascade
  ) tablespace pg_default;

create table
  public.feedback (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    created_by bigint not null,
    text text not null,
    constraint feedback_pkey primary key (id),
    constraint feedback_created_by_fkey foreign key (created_by) references users (id) on delete cascade
  ) tablespace pg_default;

create table
  public.files (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    rating numeric not null default '1'::numeric,
    name text null,
    mimetype text not null default 'image/jpg'::text,
    published boolean not null default true,
    keywords jsonb[] not null default '{}'::jsonb[],
    constraint files_pkey primary key (id)
  ) tablespace pg_default;


  